### ISSUE TITLE
Payment gateway

### ISSUE THREAD

**Issue by Elenium123** [nartj/sellix-woocommerce#3]
Hey, as soon as customers press complete in the checkout it says this
![unknown-2](https://user-images.githubusercontent.com/81765835/113469881-c8651500-9459-11eb-9f6c-9e5638731023.png)

**Comment by nartj** [comment]
Hello, 
If I understand correctly, this error is fired on the payement checkout page, not directly on your website, right ? 
Can you paste an example url from where you can see this error ?

**Comment by Elenium123** [comment]
![image](https://user-images.githubusercontent.com/81765835/113474387-6536ab00-9478-11eb-8cfe-3bacdd9386a8.png)
https://eleniummods.com/checkout/

**Comment by nartj** [comment]
Ok.
And the process was working correctly yesterday ?

**Comment by Elenium123** [comment]
Yes, a few transactions happened yesterday

**Comment by nartj** [comment]
did you changed something since yesterday ?

**Comment by Elenium123** [comment]
Nope, incase someone did i tried reinstalling the plugin but still same thing

**Comment by nartj** [comment]
Bizarre. 
I will add logs in an hour or two to investigate the problem.

**Comment by nartj** [comment]
Check sellix plugin configuration in your wordpress admin page

**Comment by Elenium123** [comment]
![image](https://user-images.githubusercontent.com/81765835/113474608-906dca00-9479-11eb-95bb-407d117b9772.png)
Nothing seems to be wrong, i even double-checked the API key

**Comment by nartj** [comment]
Seems to be right yes

**Comment by Elenium123** [comment]
It seems to be working now somehow, never did anything lets keep this open for a while to be sure

**Comment by nartj** [comment]
No problem. 
Maybe the issue was on sellix side

**Comment by nartj** [comment]
Closing this, feel free to reopen the issue if the bug reappears, I will investigate at this moment.
