### ISSUE TITLE
Orders aren't getting completed after payment

### ISSUE THREAD

**Issue by Elenium123** [nartj/sellix-woocommerce#4]
Howdy!
I referred a friend of mine to your plugin and we both use them now, mine's working perfectly but he has the firs problem that i had, which is after customers pay the order doesn't get set as completed. I'll help him out with the logs and stuff like that

**Comment by nartj** [comment]
Hi,
Use the latest version of the plugin (https://github.com/nartj/sellix-woocommerce/releases/download/1.0.3/sellix-woocommerce-1.0.3.zip)

**Comment by nartj** [comment]
Do you have some news?

**Comment by Elenium123** [comment]
Hey! Sorry for taking a while, still doesn't seem to be working for my friend's site

**Comment by nartj** [comment]
I will do a debug release so that you can test with him and send me logs

**Comment by Elenium123** [comment]
Sounds good!

**Comment by nartj** [comment]
Hey dude, 
I pushed a new release with a debug mode integrated. You can found it there https://github.com/nartj/sellix-woocommerce/releases/download/1.0.4/sellix-woocommerce-1.0.4.zip
Just enable debug mode in your sellix plugin configuration, then tests a payment and see logs as usual.
You can send me the logs of your friend who has difficulties with the plugin.

**Comment by Elenium123** [comment]
[php-errors (8).log](https://github.com/nartj/sellix-woocommerce/files/6307101/php-errors.8.log)
Once i'm at the checkout page, i press on "place order" and nothing happens

**Comment by Elenium123** [comment]
[php-errors (9).log](https://github.com/nartj/sellix-woocommerce/files/6307111/php-errors.9.log)
Here is another one, forgot to turn on debug mode

**Comment by nartj** [comment]
I found problems in my latest release concerning debug mode.
I push a new release. Please test it and send logs there.

**Comment by Elenium123** [comment]
Alright will test it as soon as my friend comes on

**Comment by Elenium123** [comment]
[php-errors (11).log](https://github.com/nartj/sellix-woocommerce/files/6321304/php-errors.11.log)
NOTE: Order 2449 is the one that i tested in

**Comment by nartj** [comment]
Is this the issue ? 
Sellix Payment creation concerning order 2420 returned: {"status":400,"data":null,"message":null,"log":null,"error":"**The order total cannot be lower than USD 0.50.**","env":"production"}

**Comment by nartj** [comment]
The webhook doesn't seem to be called

**Comment by Elenium123** [comment]
How so? I made an order and fully paid

**Comment by nartj** [comment]
I don't know. All I see is the logs in the webhook method aren't reached. Sellix is responsible of calling the webhook url you give.

**Comment by nartj** [comment]
Any update on this?

**Comment by Elenium123** [comment]
Still can't seem to get it working

**Comment by nartj** [comment]
did he tried to contact sellix to be sure the webhook is correctly called?
Also, you could download tools like Postman or Insomnia to manually do the call to the webhook and see if it got logs of that call in your logs (in debug mode). I can help you on that if you want to do it like that.

**Comment by Elenium123** [comment]
My friend just fixed it, it was because of the DDoS protection thingy.
