### ISSUE TITLE
Image Path is wrongly configured [Sellix Logo]

### ISSUE THREAD

**Issue by mindstop** [nartj/sellix-woocommerce#5]
The image path is wrong configured due to which the logo is not displayed in checkout page.

Path configured :  '/sellix-woocommerce/assets/sellix.png');

Path that should be configured :  '/sellix-woocommerce-1.0.5/assets/sellix.png');

**Comment by nartj** [comment]
Hi,
Thanks for pointing out the issue.
It is corrected on the latest release, please download it and update your plugin.
I prefere to let /sellix-woocommerce/assets/sellix.png', thus I changed the directory inside the plugin archive to be 'sellix-woocommerce'.
Closing this.
